##################################################
# HEADER TEMPERATURES
##################################################

sensor:

  - platform: homeassistant
    id: indoor_temp
    entity_id: sensor.family_s_echo_temperature
    trigger_on_initial_state: true
    on_value:
      - script.execute: update_header

  - platform: homeassistant
    id: outdoor_temp
    entity_id: weather.forecast_home
    attribute: temperature
    trigger_on_initial_state: true
    on_value:
      - script.execute: update_header


##################################################
# ENERGY
##################################################

  - platform: homeassistant
    id: solar_today
    entity_id: sensor.solar_daily_production_kwh
    trigger_on_initial_state: true
    on_value:
      - lvgl.label.update:
          id: solar_value
          text:
            format: "%.1f kWh"
            args: ['x']

  - platform: homeassistant
    id: usage_today
    entity_id: sensor.envoy_122429013109_energy_consumption_today
    trigger_on_initial_state: true
    on_value:
      - lvgl.label.update:
          id: usage_value
          text:
            format: "%.1f kWh"
            args: ['x']

  - platform: homeassistant
    id: car_battery
    entity_id: sensor.ky22mdv_battery
    trigger_on_initial_state: true
    on_value:
      - lvgl.label.update:
          id: car_value
          text:
            format: "%.0f %%"
            args: ['x']


##################################################
# TEXT SENSORS
##################################################

text_sensor:

  - platform: homeassistant
    id: rain_status
    entity_id: sensor.rain_status_text
    trigger_on_initial_state: true
    on_value:
      - lvgl.label.update:
          id: rain_value
          text: !lambda return x;

  - platform: homeassistant
    id: weather_status
    entity_id: weather.forecast_home
    attribute: condition
    trigger_on_initial_state: true
    on_value:
      - lvgl.label.update:
          id: weather_value
          text: !lambda return x;


##################################################
# HEADER SCRIPT
##################################################

script:
  - id: update_header
    then:
      - lambda: |-
          if (!id(indoor_temp).has_state() ||
              !id(outdoor_temp).has_state())
            return;

          char buf[32];
          snprintf(buf,sizeof(buf),"%d° / %d°",
            (int)round(id(indoor_temp).state),
            (int)round(id(outdoor_temp).state));

          lv_label_set_text(id(temperatures), buf);
